use crate::models::{RiskLevel, SupportLevel};

#[derive(Debug, Clone, Copy)]
pub struct DataPathRule {
    pub relative_path: &'static str,
    pub category_id: &'static str,
    pub label: &'static str,
    pub description: &'static str,
    pub source_type: &'static str,
    pub risk_level: RiskLevel,
    pub reviewable: bool,
    pub regenerable: bool,
    pub protected: bool,
    pub requires_app_quit: bool,
}

#[derive(Debug, Clone)]
pub struct AppRule {
    pub rule_id: &'static str,
    pub app_name: &'static str,
    pub bundle_ids: &'static [&'static str],
    pub bundle_names: &'static [&'static str],
    pub category: &'static str,
    pub support_level: SupportLevel,
    pub glyph: &'static str,
    pub color: &'static str,
    pub data_paths: &'static [DataPathRule],
}

const CAPCUT_PATHS: &[DataPathRule] = &[
    DataPathRule {
        relative_path: "Library/Caches/com.lemon.lvpro",
        category_id: "preview-cache",
        label: "预览与临时缓存",
        description: "剪辑预览和可重建临时数据，本轮只展示、不处理。",
        source_type: "cache",
        risk_level: RiskLevel::Safe,
        reviewable: true,
        regenerable: true,
        protected: false,
        requires_app_quit: true,
    },
    DataPathRule {
        relative_path: "Library/Application Support/JianyingPro",
        category_id: "application-support",
        label: "应用数据",
        description: "可能混合配置、草稿索引和媒体数据，必须查看后判断。",
        source_type: "application_support",
        risk_level: RiskLevel::Review,
        reviewable: true,
        regenerable: false,
        protected: false,
        requires_app_quit: true,
    },
    DataPathRule {
        relative_path: "Movies/JianyingPro",
        category_id: "projects",
        label: "工程与素材",
        description: "用户工程、素材或导出内容，不允许直接处理。",
        source_type: "project",
        risk_level: RiskLevel::Protected,
        reviewable: false,
        regenerable: false,
        protected: true,
        requires_app_quit: false,
    },
];

const WECHAT_PATHS: &[DataPathRule] = &[
    DataPathRule {
        relative_path: "Library/Caches/com.tencent.xinWeChat",
        category_id: "cache",
        label: "临时缓存",
        description: "可重建缓存，本轮仅标记为建议检查。",
        source_type: "cache",
        risk_level: RiskLevel::Safe,
        reviewable: true,
        regenerable: true,
        protected: false,
        requires_app_quit: true,
    },
    DataPathRule {
        relative_path: "Library/Containers/com.tencent.xinWeChat",
        category_id: "chat-data",
        label: "聊天与应用数据",
        description: "可能包含聊天记录、附件和数据库，不允许直接处理。",
        source_type: "container",
        risk_level: RiskLevel::Protected,
        reviewable: false,
        regenerable: false,
        protected: true,
        requires_app_quit: true,
    },
    DataPathRule {
        relative_path: "Library/Group Containers/5A4RE8SF68.com.tencent.xinWeChat",
        category_id: "shared-data",
        label: "共享数据",
        description: "微信共享容器，可能包含用户内容和数据库。",
        source_type: "group_container",
        risk_level: RiskLevel::Protected,
        reviewable: false,
        regenerable: false,
        protected: true,
        requires_app_quit: true,
    },
];

const XCODE_PATHS: &[DataPathRule] = &[
    DataPathRule {
        relative_path: "Library/Developer/Xcode/DerivedData",
        category_id: "derived-data",
        label: "DerivedData 构建缓存",
        description: "Xcode 可以重新生成的构建产物。",
        source_type: "build_cache",
        risk_level: RiskLevel::Safe,
        reviewable: true,
        regenerable: true,
        protected: false,
        requires_app_quit: true,
    },
    DataPathRule {
        relative_path: "Library/Developer/CoreSimulator",
        category_id: "simulators",
        label: "模拟器",
        description: "包含模拟器系统与设备数据，需要按设备检查。",
        source_type: "simulator",
        risk_level: RiskLevel::Review,
        reviewable: true,
        regenerable: false,
        protected: false,
        requires_app_quit: true,
    },
    DataPathRule {
        relative_path: "Library/Developer/Xcode/Archives",
        category_id: "archives",
        label: "发布归档",
        description: "可能用于崩溃符号化或历史发布，不允许直接处理。",
        source_type: "archive",
        risk_level: RiskLevel::Protected,
        reviewable: false,
        regenerable: false,
        protected: true,
        requires_app_quit: false,
    },
    DataPathRule {
        relative_path: "Library/Developer/Xcode/iOS DeviceSupport",
        category_id: "device-support",
        label: "设备支持文件",
        description: "连接设备时产生的支持文件，可按系统版本检查。",
        source_type: "device_support",
        risk_level: RiskLevel::Review,
        reviewable: true,
        regenerable: true,
        protected: false,
        requires_app_quit: true,
    },
];

const LARK_PATHS: &[DataPathRule] = &[
    DataPathRule {
        relative_path: "Library/Caches/com.bytedance.lark",
        category_id: "cache",
        label: "临时缓存",
        description: "飞书可重建缓存，本轮仅建议检查。",
        source_type: "cache",
        risk_level: RiskLevel::Safe,
        reviewable: true,
        regenerable: true,
        protected: false,
        requires_app_quit: true,
    },
    DataPathRule {
        relative_path: "Library/Application Support/LarkShell",
        category_id: "application-support",
        label: "应用数据",
        description: "可能混合配置、离线数据和用户内容，需要查看。",
        source_type: "application_support",
        risk_level: RiskLevel::Review,
        reviewable: true,
        regenerable: false,
        protected: false,
        requires_app_quit: true,
    },
    DataPathRule {
        relative_path: "Library/Containers/com.bytedance.ee.lark.mac",
        category_id: "container",
        label: "沙盒数据",
        description: "可能包含数据库和离线内容，不允许直接处理。",
        source_type: "container",
        risk_level: RiskLevel::Protected,
        reviewable: false,
        regenerable: false,
        protected: true,
        requires_app_quit: true,
    },
];

pub fn app_rules() -> Vec<AppRule> {
    vec![
        AppRule {
            rule_id: "capcut",
            app_name: "剪映",
            bundle_ids: &["com.lemon.lvpro", "com.lemon.lvoverseas"],
            bundle_names: &["JianyingPro.app", "CapCut.app", "剪映专业版.app"],
            category: "视频创作",
            support_level: SupportLevel::Deep,
            glyph: "剪",
            color: "#6d8dff",
            data_paths: CAPCUT_PATHS,
        },
        AppRule {
            rule_id: "wechat",
            app_name: "微信",
            bundle_ids: &["com.tencent.xinWeChat"],
            bundle_names: &["WeChat.app", "微信.app"],
            category: "沟通协作",
            support_level: SupportLevel::Deep,
            glyph: "微",
            color: "#34c985",
            data_paths: WECHAT_PATHS,
        },
        AppRule {
            rule_id: "xcode",
            app_name: "Xcode",
            bundle_ids: &["com.apple.dt.Xcode"],
            bundle_names: &["Xcode.app"],
            category: "开发工具",
            support_level: SupportLevel::Deep,
            glyph: "X",
            color: "#2fa8ff",
            data_paths: XCODE_PATHS,
        },
        AppRule {
            rule_id: "lark",
            app_name: "飞书",
            bundle_ids: &["com.bytedance.ee.lark.mac", "com.larksuite.lark"],
            bundle_names: &["Lark.app", "Feishu.app", "飞书.app"],
            category: "办公协作",
            support_level: SupportLevel::Deep,
            glyph: "飞",
            color: "#5877ff",
            data_paths: LARK_PATHS,
        },
    ]
}
